homework 1 - components using composable
Zokky2e/android-vjestina-tmdb pull request #1
Opened 2022-10-26 19:18 UTC by Zokky2e

added components for homework 1
note: asyncImage didn't return image from imageUrl, decided to send anyway

2022-10-28 12:25 UTC, fjandel-five requested changes
Homework is generally done good, but there are some things to fix together with other comments:
 -  please create Vector assets for empty and filled hearts instead of having .png, as described in homework task number 3
 - ensure every saved file ends with a line break
 - format files before creating pr -> you can do this in AS with `alt` + `cmd` + `L` shortcut

2022-10-28 12:25 UTC, fjandel-five commented on .idea/inspectionProfiles/Project_Default.xml
> +</component>
You can add this file to .gitignore

2022-10-28 12:25 UTC, fjandel-five commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/ActorCard.kt
> +}
Please configure AS to add new line at the end of file:
`Preferences -> Editor -> General -> Ensure line feed at file end on Save`

2022-10-28 12:25 UTC, fjandel-five commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/ActorCard.kt
> +       shape = RoundedCornerShape(10.dp),
It is a good practice to use shapes defined in theme, that way we can change appearance of components from one place: 
`shape = MaterialTheme.shapes.medium`

2022-10-28 12:25 UTC, fjandel-five commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/ActorCard.kt
> +       modifier = modifier.width(130.dp)
No need to define width of the card here. If we want to reuse this component but with different width, this way it won't be possible. Set width on calling site for this component:
```kotlin
ActorCard(
    // ...,
    modifier = Modifier.width(130.dp).
)
```

2022-10-28 12:25 UTC, fjandel-five commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/CrewItem.kt
> +                .padding( bottom = 2.dp),
You should pass `modifier` from function argument to the top-level function in your component. That way, you can modify the appearance of the whole component, and not just some specific inside it. 

```kotlin
Column(modifier = modifier) {
    // ....
}
```

2022-10-28 12:25 UTC, fjandel-five commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/FavoriteButton.kt
> +            .padding(4.dp)
```kotlin
.padding(MaterialTheme.spacing.extraSmall)
```

2022-10-28 12:25 UTC, fjandel-five commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/FavoriteButton.kt
> +    Image(
We want our components to be stateless. You can read more about it [here](https://developer.android.com/jetpack/compose/state#state-hoisting). 
Add function which will be called when FavoriteButton is clicked:
```kotlin
@Composable
fun FavoriteButton(
    isFavorite: Boolean,
    onClick: () -> Unit,
    modifier: Modifier = Modifier,
) {
```

2022-10-28 12:25 UTC, fjandel-five commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/FavoriteButton.kt
> +                isFavoriteState = isFavoriteState.not()
replace with: `onClick()`

2022-10-28 12:25 UTC, fjandel-five commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/FavoriteButton.kt
> +
Here you'll hoist `isFavorite` state when you change your FavoriteButton:

```kotlin
var isFavorite by remember { mutableStateOf(true) }
    FavoriteButton(
        isFavorite = isFavorite,
        onClick = { isFavorite = !isFavorite }
    )
```

2022-10-28 12:25 UTC, fjandel-five commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/main/MainActivity.kt
> +
remove redundant empty line

2022-10-28 12:25 UTC, fjandel-five commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/MovieCard.kt
> +        )
format

2022-10-28 12:25 UTC, fjandel-five commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/ActorCard.kt
> +                  .build(),
```kotlin
model = actorCardViewState.imageUrl,
```

2022-10-28 12:25 UTC, fjandel-five commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/MovieCard.kt
> +                model = ImageRequest.Builder(LocalContext.current).data(movieCardViewState.imageUrl).build(),
```kotlin
model = movieCardViewState.imageUrl,
```

2022-10-28 12:25 UTC, fjandel-five commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/MovieCard.kt
> +        modifier = modifier.size(130.dp, 200.dp)
```kotlin
Card(
    shape = MaterialTheme.shapes.medium,
    elevation = 10.dp,
    modifier = modifier,
    onClick = onCardClick
)
```

```kotlin
MovieCard(
    // ...,
    modifier = Modifier.size(130.dp, 200.dp)
)
```

2022-10-28 12:25 UTC, fjandel-five commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/MovieCard.kt
> +    modifier: Modifier = Modifier
```kotlin
@Composable
fun MovieCard(
    movieCardViewState: MovieCardViewState,
    onCardClick: () -> Unit,
    onLikeButtonClick: () -> Unit,
    modifier: Modifier = Modifier,
) {
    // ...
}
```

2022-10-28 12:25 UTC, fjandel-five commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/MovieCard.kt
> +                    .clickable {}
remove this

2022-10-28 12:25 UTC, fjandel-five commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/MovieCard.kt
> +        }
you'll pass here `onClick = onLikeButtonClick`

2022-10-28 12:25 UTC, fjandel-five commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/MovieCategoryLabel.kt
> +class MovieCategoryLabelTextViewStateReferenced(@StringRes val textRes: Int): MovieCategoryLabelTextViewState()
It is more readable to nest subclasses inside definition of sealed class. Also, that way you don't have to prefix those classes:

```kotlin
sealed class MovieCategoryLabelTextViewState {
    data class Text(val text: String) : MovieCategoryLabelTextViewState()
    data class TextRes(@StringRes val textRes: Int) : MovieCategoryLabelTextViewState()
}
```

2022-10-28 12:25 UTC, fjandel-five commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/MovieCategoryLabel.kt
> +) {
```kotlin
@Composable
fun MovieCategoryLabel(
    movieCategoryLabelUiState: MovieCategoryLabelViewState,
    onItemClick: (MovieCategoryLabelViewState) -> Unit,
    modifier: Modifier = Modifier,
)
```

2022-10-28 12:25 UTC, fjandel-five commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/MovieCategoryLabel.kt
> +    var isSelectedState by remember { mutableStateOf(movieCategoryLabelViewState.isSelected) }
remove this

2022-10-28 12:25 UTC, fjandel-five commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/MovieCategoryLabel.kt
> +    Column(modifier = modifier.width(IntrinsicSize.Min))
add: `.clickable { onItemClick(movieCategoryLabelUiState) }`

2022-10-28 12:25 UTC, fjandel-five commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/UserScoreProgressBar.kt
> +                Color(red=212, green =255,blue=212),
If you introducing some new color, please add it in `Color.kt` file, and than call it from there

2022-10-28 12:25 UTC, fjandel-five commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/UserScoreProgressBar.kt
> +                sweepAngle = (1-progress)*360,
`360`, `90` are [magic numbers](https://en.wikipedia.org/wiki/Magic_number_(programming)). Please extract them as private constants, something like this:

```kotlin
private const val DEGREES_IN_CIRCLE = 360f
private const val STARTING_POSITION = 90f
```

2022-10-29 07:59 UTC, Zokky2e commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/ActorCard.kt
> +}
not sure if you wanted me to have an empty line after row 70, but doing this "ensure line feed at file end on save" made an empty line at the end of the file

2022-11-08 10:27 UTC, fjandel-five requested changes

2022-11-08 10:27 UTC, fjandel-five commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/FavoriteButton.kt
> +    onClick: () -> Unit,
reorder arguments so the mandatory ones comes first:

```kotlin
isFavorite: Boolean,
onClick: () -> Unit,
modifier: Modifier = Modifier
```

2022-11-08 10:27 UTC, fjandel-five commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/MovieCard.kt
> +        Box(modifier = Modifier) {
No need for usage of default `Modifier` here.

2022-11-08 10:27 UTC, fjandel-five commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/MovieCard.kt
> +                modifier
`Modifier` instead of `modifier`

2022-11-08 10:27 UTC, fjandel-five commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/MovieCard.kt
> +                    .size(130.dp, 200.dp)
provide size through component `modifier`, and here use `Modifier.fillMaxSize()`

2022-11-08 10:27 UTC, fjandel-five commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/MovieCard.kt
> +                    .clickable{onLikeButtonClick()}
remove this as you passing `onLikeButtonClick` already through component parameter

2022-11-08 10:27 UTC, fjandel-five commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/MovieCategoryLabel.kt
> +            modifier = modifier.clickable { onItemClick(movieCategoryLabelViewState) }
put this clickable modifier to `Column` subcomponent as we want the whole component to be clickable

2022-11-12 14:39 UTC, merged